# Generated by Django 4.0.4 on 2022-07-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categorybrand'),
        ),
    ]
