# Generated by Django 4.0.4 on 2022-07-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_color_level_alter_size_level_alter_tag_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
