# Generated by Django 4.0.4 on 2022-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='all_price',
            field=models.FloatField(default=0),
        ),
    ]
