# Generated by Django 4.0.4 on 2022-07-17 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cartitem_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 19, 16, 54, 303195)),
        ),
    ]
