# Generated by Django 4.0.4 on 2022-07-21 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subscribe_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 3, 6, 55, 495268)),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('rating', models.FloatField(default=0)),
                ('text', models.TextField(blank=True)),
                ('data', models.DateTimeField()),
                ('comment_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.good')),
            ],
        ),
    ]
