# Generated by Django 4.0.4 on 2022-07-23 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cart_created_at_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 0, 38, 43, 336051)),
        ),
    ]
