# Generated by Django 4.0.4 on 2022-07-23 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_good_discount_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 0, 39, 41, 216174)),
        ),
        migrations.AlterField(
            model_name='good',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
